name: test

on:  
  push:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Ethernaut Solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        env:
          SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
        id: test

  coverage:
    runs-on: ubuntu-latest
    env:
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run coverage
        run: forge coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

